version: '2'

services:
  rabbithole:
    container_name: MessageBroker-RabbithHole
    image: rabbithole
    environment:
      RABBITMQ_ENDPOINT: 172.19.0.2
      RABBITMQ_USERNAME: picasouser
      RABBITMQ_PASSWORD: iamill
    ports:
     - 50000:50000
    build:
      context: ./RabbitHole
      dockerfile: Dockerfile
    networks:
      default:
        ipv4_address: 172.19.0.3

networks:
  default:
    external:
      name: MessageBroker